/*
 * [문제 정보] 5월 식품들의 총매출 조회하기
 * [사용 SQL] JOIN, WHERE, GROUP BY, SUM, ORDER BY
 *
 * [풀이 핵심]
 * 1. FOOD_PRODUCT와 FOOD_ORDER를 PRODUCT_ID 기준으로 JOIN.
 * 2. 2022년 5월 주문 데이터만 WHERE로 필터링.
 * 3. 상품별 총매출을 구하기 위해 PRODUCT_ID, PRODUCT_NAME으로 GROUP BY.
 * 4. 총매출은 상품 가격(PRICE) × 주문수량(AMOUNT)을 합산하여 계산.
 * 5. 총매출을 내림차순으로 정렬하고, 동일한 경우 PRODUCT_ID를 오름차순 정렬.
 */
 
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(P.PRICE * O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P JOIN FOOD_ORDER O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE O.PRODUCE_DATE >= '2022-05-01' AND O.PRODUCE_DATE < '2022-06-01'
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY SUM(P.PRICE * O.AMOUNT) DESC, P.PRODUCT_ID ASC;